// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRhf4p-_v7NiYdMj55h739bgftNLhq8E',
    appId: '1:880694138298:web:c3ea10b606d543fb1bf983',
    messagingSenderId: '880694138298',
    projectId: 'travelbuddy-sih-2026-anuj',
    authDomain: 'travelbuddy-sih-2026-anuj.firebaseapp.com',
    storageBucket: 'travelbuddy-sih-2026-anuj.firebasestorage.app',
    measurementId: 'G-8CMSHK883Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TfPPAufzpeY1ev4r4tZElURv9Sz_ZC0',
    appId: '1:880694138298:android:9b63c5a875fa95641bf983',
    messagingSenderId: '880694138298',
    projectId: 'travelbuddy-sih-2026-anuj',
    storageBucket: 'travelbuddy-sih-2026-anuj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpSRRCr_pbSItpYWH4puQFq4ellxjqQM',
    appId: '1:880694138298:ios:4dea6f2ea07b38961bf983',
    messagingSenderId: '880694138298',
    projectId: 'travelbuddy-sih-2026-anuj',
    storageBucket: 'travelbuddy-sih-2026-anuj.firebasestorage.app',
    iosBundleId: 'com.example.safeYatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWpSRRCr_pbSItpYWH4puQFq4ellxjqQM',
    appId: '1:880694138298:ios:4dea6f2ea07b38961bf983',
    messagingSenderId: '880694138298',
    projectId: 'travelbuddy-sih-2026-anuj',
    storageBucket: 'travelbuddy-sih-2026-anuj.firebasestorage.app',
    iosBundleId: 'com.example.safeYatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkRhf4p-_v7NiYdMj55h739bgftNLhq8E',
    appId: '1:880694138298:web:bb9aa7f0e4e9f87c1bf983',
    messagingSenderId: '880694138298',
    projectId: 'travelbuddy-sih-2026-anuj',
    authDomain: 'travelbuddy-sih-2026-anuj.firebaseapp.com',
    storageBucket: 'travelbuddy-sih-2026-anuj.firebasestorage.app',
    measurementId: 'G-NYMNQDFHHR',
  );
}
